[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Configuración específica para formularios
[build.processing]
  skip_processing = false

# Configuración para formularios
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración para formularios
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración específica para formularios
[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://storage.ko-fi.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.netlify.com;"
